Update

diff --git a/.github/workflows/ci-cd-pipeline.yml b/.github/workflows/ci-cd-pipeline.yml
--- a/.github/workflows/ci-cd-pipeline.yml
+++ b/.github/workflows/ci-cd-pipeline.yml
@@ -67,17 +67,17 @@ jobs:
             
             - name: Show The Artiface
               run: |
-                ls -a
+                ls -Force
 
             - name: Install The Package
               run: npm install
             
             - name: Run The Application By PM2
               run: |
-                ls -a
+                ls -Force
                 pm2 status
                 # delete node-app process
-                pm2 delete node-app || true
+                pm2 delete node-app; if ($?) { echo "Deleted successfully" } else { echo "Process not found" }
 
                 # pm2 restart all
 
